60322_Ivanov_Egor/60322_Ivanov_Egor/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _60322_Ivanov_Egor.DAL.Entities;
using _60322_Ivanov_Egor.DAL.Repositories;
using _60322_Ivanov_Egor.DAL.Interfaces;

namespace _60322_Ivanov_Egor.Controllers
{
    public class AdminController : Controller
    {
        IRepository<Product> repository;
        public AdminController(IRepository<Product> repo)
        {
            repository = repo;
        }
        // GET: Admin
        public ActionResult Index()
        {
            return View(repository.GetAll());

        }


        // GET: Admin/Create
        public ActionResult Create()
        {
            return View(new Product());
        }

        // POST: Admin/Create
        [HttpPost]
        public ActionResult Create(Product prod, HttpPostedFileBase imageUpload = null)
        {
            if (imageUpload != null)
            {
                var count = imageUpload.ContentLength;
                prod.ProdImage = new byte[count];
                imageUpload.InputStream.Read(prod.ProdImage, 0, (int)count);
                prod.MimeType = imageUpload.ContentType;
            }
            try
            {
                repository.Create(prod);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(prod);
            }
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View(repository.Get(id));
        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase imageUpload = null)
        {
            if (ModelState.IsValid)
            {
                if (imageUpload != null)
                {
                    var count = imageUpload.ContentLength;
                    product.ProdImage = new byte[count];
                    imageUpload.InputStream.Read(product.ProdImage, 0, (int)count);
                    product.MimeType = imageUpload.ContentType;
                }
                try
                {
                    repository.Update(product);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            else
            {
                return View(product);
            }
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

60322_Ivanov_Egor/60322_Ivanov_Egor/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _60322_Ivanov_Egor.DAL.Interfaces;
using _60322_Ivanov_Egor.DAL.Entities;
using _60322_Ivanov_Egor.Models;
using System.Threading.Tasks;

namespace _60322_Ivanov_Egor.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        int pageSize = 5; // the qty of elements showed in a page
        IRepository<Product> repository;
        public ProductController(IRepository<Product> repository)
        {
            this.repository = repository;
        }
        public ActionResult List(string group, int page = 1)
        {
            var lst = repository.GetAll()
            .Where(d => group == null
            || d.ProdCategory.Equals(group))
            .OrderBy(d => d.ProdPrice);
            var model = PageListViewModel<Product>.CreatePage(lst, page, pageSize);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ListPartial", model);
            }
            return View(model);
        }

        public async Task<FileResult> GetImage(int id)
        {
            Product prod = await repository.GetAsync(id);
            if (prod != null)
                return File(prod.ProdImage, prod.MimeType);
            else
                return null;
        }
    }
}

60322_Ivanov_Egor/60322_Ivanov_Egor/Views/Admin/Create.cshtml
@model _60322_Ivanov_Egor.DAL.Entities.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProdId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdCategory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
             @Html.Label("Выберите файл",htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                <input type="file" name="imageUpload" class="form-control" />
             </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                @if (Model.ProdImage == null)
                {<p>Нет изображения</p>}
                else
                {
                    <img width="150" height="150" src="@Url.Action("GetImage", "Product", 
                             new {id=Model.ProdId })" class="img-thumbnail"> }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

60322_Ivanov_Egor/60322_Ivanov_Egor/Views/Admin/Edit.cshtml
@model _60322_Ivanov_Egor.DAL.Entities.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProdId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdCategory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Выберите файл",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imageUpload" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                @if (Model.ProdImage == null)
                {<p>Нет изображения</p>}
                else
                {
                    <img width="150" height="150" src="@Url.Action("GetImage", "Product",
                             new {id=Model.ProdId })" class="img-thumbnail"> }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

60322_Ivanov_Egor/60322_Ivanov_Egor/Views/Admin/Index.cshtml
@model IEnumerable<_60322_Ivanov_Egor.DAL.Entities.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Добавить", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProdId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdCategory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdPrice)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProdId)
        </td>
        <td>
            @Html.ActionLink(@Html.DisplayFor(modelItem =>item.ProdName).ToString(), "Edit", new { id = item.ProdId })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdCategory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdPrice)
        </td>

        <td>
            @Html.ActionLink("Удалить", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>